{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"fnBasicCalendarWithChoiceForStartOfWeek\",\"DimCompanyCalendar\",\"HolidayTable\",\"CalendarDim\",\"DimTempCalendar\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.119.666.0 (23.07)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "fnBasicCalendarWithChoiceForStartOfWeek",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = let fnDateTable = (StartDate as date, EndDate as date, optional FYStartMonthNum as number, optional Holidays as list, optional StartOfWeekDay as number, optional WDStartNum as number ) as table =>",
          "  let",
          "    FYStartMonth = if List.Contains( {1..12}, FYStartMonthNum ) then FYStartMonthNum else 1,",
          "    StartOfWeekDayNum = if List.Contains( {0..6}, StartOfWeekDay ) then StartOfWeekDay else 1,",
          "    WDStart = if List.Contains( {0, 1}, WDStartNum ) then WDStartNum else 0,",
          "    CurrentDate = Date.From(DateTime.FixedLocalNow()),",
          "    DayCount = Duration.Days(Duration.From(EndDate - StartDate))+1,",
          "    Source = List.Dates(StartDate,DayCount,#duration(1,0,0,0)),",
          "    AddToday = if EndDate < CurrentDate then List.Combine( {Source, {CurrentDate}}) else Source,",
          "    TableFromList = Table.FromList(AddToday, Splitter.SplitByNothing()),",
          "    ChangedType = Table.TransformColumnTypes(TableFromList,{{\"Column1\", type date}}),",
          "    RenamedColumns = Table.RenameColumns(ChangedType,{{\"Column1\", \"Date\"}}),",
          "    InsertYear = Table.AddColumn(RenamedColumns, \"Year\", each Date.Year([Date]), type number),",
          "    InsertYearOffset = Table.AddColumn(InsertYear, \"YearOffset\", each Date.Year([Date]) - Date.Year(Date.From(CurrentDate)), type number),",
          "    InsertCompletedYear = Table.AddColumn(InsertYearOffset, \"YearCompleted\", each Date.EndOfYear([Date]) < Date.From(Date.EndOfYear(CurrentDate)), type logical),",
          "",
          "    InsertQuarter = Table.AddColumn(InsertCompletedYear, \"QuarterOfYear\", each Date.QuarterOfYear([Date]), type number),",
          "    InsertCalendarQtr = Table.AddColumn(InsertQuarter, \"Quarter & Year\", each \"Q\" & Number.ToText([QuarterOfYear]) & \" \" & Number.ToText([Year]), type text),",
          "    InsertQuarternYear = Table.AddColumn(InsertCalendarQtr, \"QuarternYear\", each [Year] * 10000 + [QuarterOfYear] * 100, type number),",
          "    InsertQuarterOffset = Table.AddColumn(InsertQuarternYear, \"QuarterOffset\", each ((4 * Date.Year([Date])) +  Date.QuarterOfYear([Date])) - ((4 * Date.Year(Date.From(CurrentDate))) +  Date.QuarterOfYear(Date.From(CurrentDate))), type number),",
          "    InsertCompletedQuarter = Table.AddColumn(InsertQuarterOffset, \"QuarterCompleted\", each Date.EndOfQuarter([Date]) < Date.From(Date.EndOfQuarter(CurrentDate)), type logical),",
          "",
          "    InsertMonth = Table.AddColumn(InsertCompletedQuarter, \"MonthOfYear\", each Date.Month([Date]), type number),",
          "    InsertDay = Table.AddColumn(InsertMonth, \"DayOfMonth\", each Date.Day([Date]), type number),",
          "    InsertMonthName = Table.AddColumn(InsertDay, \"Month Name\", each Text.Proper( Date.ToText([Date], \"MMMM\")), type text),",
          "    InsertMonthShort = Table.AddColumn( InsertMonthName, \"MonthShortName\", each try Text.Proper( Text.Start([Month Name], 3 )) otherwise Text.Proper( [Month Name] ), type text),",
          "    InsertMonthInitial = Table.AddColumn(InsertMonthShort, \"Month Initial\", each Text.Proper(Text.Start([Month Name], 1)) & Text.Repeat( Character.FromNumber(8203), [MonthOfYear] ), type text),",
          "    InsertCalendarMonth = Table.AddColumn(InsertMonthInitial, \"Month & Year\", each [MonthShortName] & \" \" & Number.ToText([Year]), type text),",
          "    InsertMonthnYear = Table.AddColumn(InsertCalendarMonth , \"MonthnYear\", each [Year] * 10000 + [MonthOfYear] * 100, type number),",
          "    InsertMonthOffset = Table.AddColumn(InsertMonthnYear, \"MonthOffset\", each ((12 * Date.Year([Date])) +  Date.Month([Date])) - ((12 * Date.Year(Date.From(CurrentDate))) +  Date.Month(Date.From(CurrentDate))), type number),",
          "    InsertCompletedMonth = Table.AddColumn(InsertMonthOffset, \"MonthCompleted\", each Date.EndOfMonth([Date]) < Date.From(Date.EndOfMonth(CurrentDate)), type logical),",
          "    InsertMonthEnding = Table.AddColumn(InsertCompletedMonth, \"MonthEnding\", each Date.EndOfMonth([Date]), type date),",
          "",
          "    InsertDayInt = Table.AddColumn(InsertMonthEnding, \"DateInt\", each [Year] * 10000 + [MonthOfYear] * 100 + [DayOfMonth], type number),",
          "    InsertDayOfYear = Table.AddColumn(InsertDayInt, \"Day of Year\", each Date.DayOfYear([Date]), Int64.Type),",
          "    InsertDayWeek = Table.AddColumn(InsertDayOfYear, \"DayOfWeek\", each Date.DayOfWeek([Date], StartOfWeekDayNum ) + WDStart, Int64.Type),",
          "    InsertDayName = Table.AddColumn(InsertDayWeek, \"DayOfWeekName\", each Text.Proper( Date.ToText([Date], \"dddd\" )), type text),",
          "    InsertDayInitial = Table.AddColumn(InsertDayName, \"Weekday Initial\", each Text.Proper(Text.Start([DayOfWeekName], 1)) & Text.Repeat( Character.FromNumber(8203), [DayOfWeek] ), type text),",
          "  ",
          "    InsertWeekStart = Table.AddColumn(InsertDayInitial, \"WeekStarting\", each Date.StartOfWeek( [Date], StartOfWeekDayNum), type date),",
          "    InsertWeekOffset = Table.AddColumn(InsertWeekStart, \"WeekOffset\", each (Number.From(Date.StartOfWeek([Date], StartOfWeekDayNum))-Number.From(Date.StartOfWeek(CurrentDate, StartOfWeekDayNum)))/7, type number),",
          "    InsertCompletedWeek = Table.AddColumn(InsertWeekOffset, \"WeekCompleted\", each Date.EndOfWeek( [Date], StartOfWeekDayNum) < Date.From(Date.EndOfWeek(CurrentDate, StartOfWeekDayNum)), type logical),",
          "    InsertWeekEnding = Table.AddColumn(InsertCompletedWeek, \"WeekEnding\", each Date.EndOfWeek( [Date], StartOfWeekDayNum), type date),",
          "",
          "    AddFY = Table.AddColumn(InsertWeekEnding, \"Fiscal Year\", each \"FY\" & (if [MonthOfYear] >= FYStartMonth and FYStartMonth >1 then Text.PadEnd( Text.End( Text.From([Year] +1), 2), 2, \"0\") else Text.End( Text.From([Year]), 2)), type text),",
          "    AddFQ = Table.AddColumn(AddFY, \"Fiscal Quarter\", each \"FQ\" & Text.From( Number.RoundUp( Date.Month( Date.AddMonths( [Date], - (FYStartMonth -1) )) / 3 )), type text),",
          "    AddFQnYr = Table.AddColumn(AddFQ, \"FQuarternYear\", each (if [MonthOfYear] >= FYStartMonth and FYStartMonth >1 then [Year] +1 else [Year]) * 10000 + Number.RoundUp( Date.Month( Date.AddMonths( [Date], - (FYStartMonth -1) )) / 3 ) * 100, type number),",
          "    AddFM = Table.AddColumn(AddFQnYr, \"Fiscal Period\", each if [MonthOfYear] >= FYStartMonth and FYStartMonth >1 then [MonthOfYear] - (FYStartMonth-1) else if [MonthOfYear] >= FYStartMonth and FYStartMonth =1 then [MonthOfYear] else [MonthOfYear] + (12-FYStartMonth+1), type number),",
          "    AddFMnYr = Table.AddColumn(AddFM , \"FPeriodnYear\", each (if [MonthOfYear] >= FYStartMonth and FYStartMonth >1 then [Year] +1 else [Year]) * 10000 + [Fiscal Period] * 100, type number),",
          "    FYCalendarStart = #date( Date.Year(StartDate)-1, FYStartMonth, 1 ),",
          "    InsertFFD = Table.AddColumn( AddFMnYr, \"FiscalFirstDay\", each if [MonthOfYear] >= FYStartMonth and FYStartMonth >1 then #date( Date.Year([Date])+1, FYStartMonth, 1) else #date( Date.Year([Date]), FYStartMonth, 1) ),",
          "    AddFYDateRange = Table.Buffer( Table.ExpandTableColumn( Table.ExpandTableColumn( Table.AddColumn( Table.Group( Table.Group( Table.AddColumn( Table.AddColumn( ",
          "      Table.RenameColumns( Table.TransformColumnTypes( Table.FromList( { Number.From(FYCalendarStart)..Number.From(EndDate) }, Splitter.SplitByNothing()),{{\"Column1\", type date}}), {{\"Column1\", \"Date\"}}), ",
          "        \"FiscalFirstDay\", each if Date.Month([Date]) < FYStartMonth then #date( Date.Year([Date]), FYStartMonth, 1) else #date( Date.Year([Date])+1, FYStartMonth, 1)),",
          "        \"FWStartDate\", each  Date.AddYears(Date.StartOfWeek( [Date], StartOfWeekDayNum), 1)),",
          "        {\"FiscalFirstDay\", \"FWStartDate\"}, {{\"AllRows\", each _, type table [Date=nullable date, FiscalFirstDay=date, FWStartDate=date]}}),",
          "        {\"FiscalFirstDay\"}, {{\"AllRows2\", each _, type table [FiscalFirstDay=date, FWStartDate=date, AllRows=table]}}),",
          "        \"Custom\", each Table.AddIndexColumn( [AllRows2], \"FY Week\", 1, 1))[[Custom]],",
          "        \"Custom\", {\"FiscalFirstDay\", \"FWStartDate\", \"AllRows\", \"FY Week\"}, {\"FiscalFirstDay\", \"FWStartDate\", \"AllRows\", \"FY Week\"}),",
          "        \"AllRows\", {\"Date\"}, {\"Date\"})[[Date], [FY Week]]",
          "      ),",
          "    MergeFYW = Table.NestedJoin(InsertFFD, {\"Date\"}, AddFYDateRange, {\"Date\"}, \"AddFYWeek\", JoinKind.LeftOuter),",
          "    ExpandFYWeek = Table.TransformColumnTypes( Table.ExpandTableColumn(MergeFYW, \"AddFYWeek\", {\"FY Week\"}, {\"Fiscal Week\"}),{{\"Fiscal Week\", Int64.Type}}),",
          "    AddFYW = Table.AddColumn( ExpandFYWeek, \"Fiscal Year & Week\", each if [MonthOfYear] >= FYStartMonth and FYStartMonth >1  then Text.From( Date.Year([Date])+1) & \"-\" & Text.PadStart(Text.From([Fiscal Week]), 2, \"0\") else Text.From( Date.Year([Date])) & \"-\" & Text.PadStart( Text.From([Fiscal Week]), 2, \"0\"), type text),",
          "    InsertFWeeknYear = Table.AddColumn(AddFYW, \"FWeeknYear\", each (if [MonthOfYear] >= FYStartMonth and FYStartMonth >1  then Date.Year([Date])+1 else Date.Year([Date])) * 10000 + [Fiscal Week] * 100,  Int64.Type),",
          "    ",
          "    InsertIsAfterToday = Table.AddColumn(InsertFWeeknYear, \"IsAfterToday\", each not ([Date] <= Date.From(CurrentDate)), type logical),",
          "    InsertIsWorkingDay = Table.AddColumn(InsertIsAfterToday, \"IsWorkingDay\", each if Date.DayOfWeek([Date], Day.Monday) > 4 then false else true, type logical),",
          "    InsertIsHoliday = Table.AddColumn(InsertIsWorkingDay, \"IsHoliday\", each if Holidays = null then \"Unknown\" else List.Contains( Holidays, [Date] ), if Holidays = null then type text else type logical),",
          "    InsertIsBusinessDay = Table.AddColumn(InsertIsHoliday, \"IsBusinessDay\", each if [IsWorkingDay] = true and [IsHoliday] <> true then true else false, type logical),",
          "    InsertDayType = Table.AddColumn(InsertIsBusinessDay, \"Day Type\", each if [IsHoliday] = true then \"Holiday\" else if [IsWorkingDay] = false then \"Weekend\" else if [IsWorkingDay] = true then \"Weekday\" else null, type text),",
          "",
          "    CurrentDateRecord = Table.SelectRows(InsertDayType, each ([Date] = CurrentDate)),",
          "    CurrentISOyear = CurrentDateRecord{0}[ISO Year],",
          "    CurrentISOqtr = CurrentDateRecord{0}[ISO QuarterOfYear],",
          "    CurrentYear = CurrentDateRecord{0}[Year],",
          "    CurrentMonth = CurrentDateRecord{0}[MonthOfYear],",
          "    CurrentFiscalFirstDay = CurrentDateRecord{0}[FiscalFirstDay],",
          "    PrevFiscalFirstDay = Date.AddYears(CurrentFiscalFirstDay, -1),",
          "    CurrentFQ = CurrentDateRecord{0}[FQuarternYear],",
          "    CurrentFP = CurrentDateRecord{0}[FPeriodnYear],",
          "    CurrentFW = CurrentDateRecord{0}[FWeeknYear],",
          "    InsertFYoffset = Table.AddColumn(InsertDayType, \"FiscalYearOffset\", each try (if [MonthOfYear] >= FYStartMonth then [Year]+1 else [Year]) - (if CurrentMonth >= FYStartMonth then CurrentYear+1 else CurrentYear) otherwise null, type number),",
          "    InsertCurrentFQ = Table.AddColumn(InsertFYoffset, \"IsCurrentFQ\", each if [FQuarternYear] = CurrentFQ then true else false, type logical),",
          "    InsertCurrentFP = Table.AddColumn(InsertCurrentFQ, \"IsCurrentFP\", each if [FPeriodnYear] = CurrentFP then true else false, type logical),",
          "    InsertCurrentFW = Table.AddColumn(InsertCurrentFP, \"IsCurrentFW\", each if [FWeeknYear] = CurrentFW then true else false, type logical),",
          "    InsertPYTD = Table.AddColumn(InsertCurrentFW, \"IsPYTD\", each if CurrentYear-1 = [Year] and [Day of Year] <= CurrentDateRecord{0}[Day of Year] then true else false, type logical),",
          "      ListPrevFYDates = List.Buffer( Table.SelectRows( Table.ExpandTableColumn( Table.NestedJoin(",
          "          Table.AddIndexColumn( Table.RenameColumns( Table.TransformColumnTypes( Table.FromList( List.Dates( PrevFiscalFirstDay, Number.From(CurrentFiscalFirstDay-PrevFiscalFirstDay),#duration(1,0,0,0)), Splitter.SplitByNothing()),{{\"Column1\", type date}}), {{\"Column1\", \"DateFY\"}}), \"Index\", 1, 1), {\"Index\"}, ",
          "          Table.AddIndexColumn( Table.RenameColumns( Table.TransformColumnTypes( Table.FromList( List.Dates( Date.AddYears( PrevFiscalFirstDay, -1), Number.From( PrevFiscalFirstDay - Date.AddYears( PrevFiscalFirstDay, -1)),#duration(1,0,0,0)), Splitter.SplitByNothing()),{{\"Column1\", type date}}), {{\"Column1\", \"DateFY\"}}), \"Index\", 1, 1)",
          "          , {\"Index\"}, \"Table\", JoinKind.LeftOuter), \"Table\", {\"DateFY\"}, {\"PrevDateFY\"}), each [DateFY] <= CurrentDate)[PrevDateFY] ),",
          "    InsertPFYTD = Table.AddColumn(InsertPYTD, \"IsPFYTD\", each if [FiscalYearOffset] = -1 and List.Contains(ListPrevFYDates, [Date] ) then true else false, type logical),",
          "    RemoveToday = Table.RemoveColumns( if EndDate < CurrentDate then Table.SelectRows(InsertPFYTD, each ([Date] <> CurrentDate)) else InsertPFYTD, {\"Day of Year\", \"FiscalFirstDay\"})",
          "  in",
          "    RemoveToday, documentation = [",
          "    Documentation.Name =  \" fxCalendar\", ",
          "    Documentation.Description = \" Date table function to create a calendar\", ",
          "    Documentation.LongDescription = \" Date table function to create a calendar\", ",
          "    Documentation.Category = \" Table\", ",
          "    Documentation.Version = \" 1.05: Changed Fiscal Period type to number\",",
          "    Documentation.Source = \" local\", ",
          "    Documentation.Author = \" Melissa de Korte\", ",
          "    Documentation.Examples = { [Description =  \" See: https://forum.enterprisedna.co/t/basic-date-table-power-query-m-function/19055\", ",
          "      Code = \" Optional paramters: #(lf)",
          "      (FYStartMonthNum) Month number the fiscal year starts, Januari if omitted #(lf) ",
          "      (Holidays) Select a query (and column) that contains a list of holiday dates #(lf) ",
          "      (StartOfWeekDay) Set start of week day by entering a value between 0-6, where 0 = sunday. If omitted weeks start on monday. #(lf)",
          "      (WDStartNum) Switch default weekday numbering from 0-6 to 1-7 by entering a 1 #(lf)",
          "      #(lf)",
          "      Important to note: #(lf)",
          "      [Fiscal Week] starts on a the selected weekday and can contain less than 7 days in a First- and/or Last Week of a FY #(lf)",
          "      [IsWorkingDay] does not take holiday dates into account  #(lf)",
          "      [IsBusinessDay] does take optional holiday dates into account  #(lf)",
          "      [IsPYTD] and [IsPFYTD] compare Previous [Day of Year] with the Current [Day of Year] number, so dates don't align in leap years\", ",
          "      Result = \" \" ] }",
          "    ] ",
          "  in ",
          "  Value.ReplaceType(fnDateTable, Value.ReplaceMetadata(Value.Type(fnDateTable), documentation))",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "ef349ef9-b5c0-429e-b1cf-3c10a2a8c68d"
      }
    ],
    "relationships": [
      {
        "name": "64c72c42-78a0-4cfe-a93c-67dcbdd7e73e",
        "fromColumn": "Date",
        "fromTable": "DimCompanyCalendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3fa67135-8887-4ca5-b512-3cd29ffd656c"
      },
      {
        "name": "ee6ed064-033d-464f-8e82-f6db1e90ecfa",
        "fromColumn": "MonthEnding",
        "fromTable": "DimCompanyCalendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_bd4d86f6-db01-4148-a8f6-f9e31fc2819d"
      },
      {
        "name": "5908360d-b513-4339-b786-2ed2621df810",
        "fromColumn": "WeekStarting",
        "fromTable": "DimCompanyCalendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_70e5ebaf-3fa2-440e-8f06-30b629a83ad1"
      },
      {
        "name": "8665f144-3286-4ea9-b143-54a15a86269b",
        "fromColumn": "WeekEnding",
        "fromTable": "DimCompanyCalendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3e9b4695-ff28-4bf9-bc58-7478673a3459"
      },
      {
        "name": "d42fd728-1117-43dd-999c-ed6f9d398df9",
        "fromColumn": "Date",
        "fromTable": "HolidayTable",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c0cfca0c-ee8c-48e9-b62b-99d84d38ca0f"
      },
      {
        "name": "4fc570e4-9193-451e-a3ef-41bb42c72bdc",
        "fromColumn": "Date",
        "fromTable": "CalendarDim",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e1326a3f-5d35-4b27-a455-f1d7ca3cbbb0"
      },
      {
        "name": "a145578b-7886-42a7-8324-a62d3a49722b",
        "fromColumn": "WeekStarting",
        "fromTable": "CalendarDim",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e171ca97-92d3-4760-a286-aa64125a152c"
      },
      {
        "name": "c0e929cc-7341-4cf0-812a-f6b1d17cb2d9",
        "fromColumn": "WeekEnding",
        "fromTable": "CalendarDim",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_6ac7e5d7-ee96-487d-b0d6-114a6a43211a"
      },
      {
        "name": "93081f06-a4dd-4821-bce3-2bd88fab721d",
        "fromColumn": "Date",
        "fromTable": "DimTempCalendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ab982fd3-afc9-4e1d-9add-ea2b435e4509"
      },
      {
        "name": "5f11c854-b6f9-46d4-b7a1-5acf7f6f8792",
        "fromColumn": "MonthEnding",
        "fromTable": "DimTempCalendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_41affdab-24ba-4b98-bfb2-94b749276feb"
      },
      {
        "name": "164fb63c-2b40-4566-b6f6-298e46e99b71",
        "fromColumn": "WeekStarting",
        "fromTable": "DimTempCalendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_bb75305e-0c47-41c5-a9c6-3f1154e2c3e1"
      },
      {
        "name": "24956400-5c65-488c-b0f2-e1295ba6e1a8",
        "fromColumn": "WeekEnding",
        "fromTable": "DimTempCalendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_bacab686-3a2c-4c0e-bb54-cd74a8b36057"
      },
      {
        "name": "3ed221aa-7940-44f2-870b-944eaa59ec7e",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Date",
        "fromTable": "CalendarHierarchy",
        "toColumn": "Date",
        "toTable": "CalendarDim"
      },
      {
        "name": "ae21d6f4-443a-45b0-9fbb-b42cd6432ff6",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Date",
        "fromTable": "CalendarHierarchy",
        "toColumn": "Date",
        "toTable": "DimCompanyCalendar"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "CalendarDim",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a946aa3a-3048-4966-b577-d7cdcab52fe1",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e1326a3f-5d35-4b27-a455-f1d7ca3cbbb0"
                },
                "isDefault": true,
                "relationship": "4fc570e4-9193-451e-a3ef-41bb42c72bdc"
              }
            ]
          },
          {
            "name": "DateInt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b6fc11f4-51d0-413b-8411-00794364e24c",
            "sourceColumn": "DateInt",
            "summarizeBy": "sum"
          },
          {
            "name": "DayOfWeekName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab75b6e0-415c-44f4-bc2d-a0f4c5dd476e",
            "sourceColumn": "DayOfWeekName",
            "summarizeBy": "none"
          },
          {
            "name": "FQuarternYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "315c2d0b-0e16-4ff5-a298-244797facc4f",
            "sourceColumn": "FQuarternYear",
            "summarizeBy": "sum"
          },
          {
            "name": "FWeeknYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "961185d2-09da-40d9-ad93-a5dd2e6a16ce",
            "sourceColumn": "FWeeknYear",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year & Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc2ba516-1319-42ce-82f4-6eae84db0e2f",
            "sourceColumn": "Fiscal Year & Week",
            "summarizeBy": "none"
          },
          {
            "name": "Month & Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e66d709a-de67-4414-aa67-7ae0bc9d37ea",
            "sourceColumn": "Month & Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "13b256f0-18b7-42da-a566-273cc24701b7",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "MonthOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a52fd693-8142-4756-a233-a006f35fd44f",
            "sourceColumn": "MonthOfYear",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "521cc8a3-72f8-4486-ba56-0c249a5e4ce6",
            "sourceColumn": "MonthOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthnYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "02e65a3c-f936-4e01-9b92-d13fd4a7e61a",
            "sourceColumn": "MonthnYear",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter & Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c977bf53-d01e-4b1f-80aa-1da528472f29",
            "sourceColumn": "Quarter & Year",
            "summarizeBy": "none"
          },
          {
            "name": "QuarterOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e787e261-616e-4dc5-850a-5abc59e466aa",
            "sourceColumn": "QuarterOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "QuarternYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cee30216-108f-4777-9902-3a10bf461afa",
            "sourceColumn": "QuarternYear",
            "summarizeBy": "sum"
          },
          {
            "name": "WeekEnding",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a66e0ee1-6e6a-4aec-bc53-f486702712db",
            "sourceColumn": "WeekEnding",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_6ac7e5d7-ee96-487d-b0d6-114a6a43211a"
                },
                "isDefault": true,
                "relationship": "c0e929cc-7341-4cf0-812a-f6b1d17cb2d9"
              }
            ]
          },
          {
            "name": "WeekOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "065c87ac-b54a-4c70-b7d7-e6429aa33344",
            "sourceColumn": "WeekOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "WeekStarting",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8368aced-8ba3-41b3-afb7-ebb5478d3c1a",
            "sourceColumn": "WeekStarting",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e171ca97-92d3-4760-a286-aa64125a152c"
                },
                "isDefault": true,
                "relationship": "a145578b-7886-42a7-8324-a62d3a49722b"
              }
            ]
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0bffc5d7-330d-4074-ad51-769875c5efa0",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "YearOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b0d30f4c-d97e-434b-9fce-ddf7b904062b",
            "sourceColumn": "YearOffset",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "1103be4f-c7d1-4ba9-a073-be4e9b2d273f",
        "measures": [
          {
            "name": "Date Range",
            "expression": "COMBINEVALUES(\" - \", MIN(DimCompanyCalendar[Date]), MAX(DimCompanyCalendar[Date]))",
            "lineageTag": "b1c04a97-786d-49be-9741-270a2b42b741"
          },
          {
            "name": "Version Control Measure",
            "expression": "\"Testing Measure in version control\"",
            "lineageTag": "172c180a-ce68-41d3-81f7-f18be13a542e"
          }
        ],
        "partitions": [
          {
            "name": "CalendarDim",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = DimCompanyCalendar,",
                "    #\"Removed Other Columns\" = Table.SelectColumns(Source,{\"Date\", \"Year\", \"Quarter & Year\", \"QuarternYear\", \"YearOffset\", \"QuarterOffset\", \"Month Name\", \"MonthOfYear\", \"Month & Year\", \"MonthnYear\", \"MonthOffset\", \"DateInt\", \"DayOfWeekName\", \"WeekStarting\", \"WeekOffset\", \"WeekEnding\", \"FQuarternYear\", \"Fiscal Year & Week\", \"FWeeknYear\"})",
                "in",
                "    #\"Removed Other Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "CalendarHierarchy",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "5779d54de9a143e0b0eaf3ffa79089f2"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "5b0c1e99-bf2f-4ee1-af84-56c35dac864a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Element",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9efee1f4-3d9d-4e65-96ed-564ce2992661",
            "sortByColumn": "Element Order",
            "sourceColumn": "[Element]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Element Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "255629d4-8da8-40a8-81a9-6bba17d0bf60",
            "sourceColumn": "[Element Order]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Level",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "9eae904a-a659-4747-a159-7d7ed53a9d7c",
            "sortByColumn": "Level Order",
            "sourceColumn": "[Level]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Level Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "25fe7b46-7e59-487d-9cf3-c8111c61f319",
            "sourceColumn": "[Level Order]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "816e3eab-056c-4cf9-aecf-37b2aa25bc2e",
            "sortByColumn": "Type Order",
            "sourceColumn": "[Type]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Type Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b66f1fd2-be6c-40ab-97d9-f8a980611ada",
            "sourceColumn": "[Type Order]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "0cd16d92-ddb7-415b-9e28-cf4d3b6e63fe",
            "sourceColumn": "[Year]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "db2c9b57-9b82-40d6-9d83-e4c29060678a",
            "sourceColumn": "[Year Order]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "73f39f29-fc6c-4a7d-9045-65a951687869",
        "measures": [
          {
            "name": "_MeasurePriorWeekStartDate",
            "expression": [
              "",
              "VAR vrMinDate = CALCULATE (",
              "    MIN ( DimCompanyCalendar[Date] ),",
              "    ALL ( DimCompanyCalendar ),",
              "    DimCompanyCalendar[WeekOffset] = -1",
              ")",
              "RETURN vrMinDate",
              ""
            ],
            "formatString": "General Date",
            "lineageTag": "82c6d6a9-15d0-4700-bb70-8f4ce366baaf"
          }
        ],
        "partitions": [
          {
            "name": "CalendarHierarchy",
            "mode": "import",
            "source": {
              "expression": [
                "",
                "VAR _Years =",
                "    SELECTCOLUMNS (",
                "        CalendarDim,",
                "        \"Date\", CalendarDim[Date],",
                "        \"Year\", \"CY'\" & CalendarDim[Year],",
                "        \"Year Order\", CalendarDim[Year],",
                "        \"Type\", \"Custom selections\",",
                "        \"Type Order\", 2,",
                "        \"Level\", \"Year\",",
                "        \"Level Order\", 1,",
                "        \"Element\", CalendarDim[Year],",
                "        \"Element Order\",",
                "            CALCULATE ( MAX ( CalendarDim[Year] ) ) * 100000 + 12000",
                "                + CALCULATE (",
                "                    COUNTROWS ( CalendarDim ),",
                "                    ALLEXCEPT ( CalendarDim, CalendarDim[Year] )",
                "                )",
                "    )",
                "VAR _Quarters =",
                "    SELECTCOLUMNS (",
                "        ADDCOLUMNS (",
                "            CalendarDim,",
                "            \"Quarter End Month Number\",",
                "                CALCULATE (",
                "                    MAX ( CalendarDim[MonthnYear] ),",
                "                    ALLEXCEPT ( CalendarDim, CalendarDim[QuarternYear] )",
                "                )",
                "        ),",
                "        \"Date\", CalendarDim[Date],",
                "        \"Year\", \"CY'\" & CalendarDim[Year],",
                "        \"Year Order\", CalendarDim[Year],",
                "        \"Type\", \"Custom selections\",",
                "        \"Type Order\", 2,",
                "        \"Level\", \"Quarter\",",
                "        \"Level Order\", 2,",
                "        \"Element\", CalendarDim[Quarter & Year],",
                "        \"Element Order\",",
                "            [Quarter End Month Number] * 1000",
                "                + CALCULATE (",
                "                    COUNTROWS ( CalendarDim ),",
                "                    ALLEXCEPT ( CalendarDim, CalendarDim[FQuarternYear] )",
                "                )",
                "    )",
                "VAR _Months =",
                "    SELECTCOLUMNS (",
                "        CalendarDim,",
                "        \"Date\", CalendarDim[Date],",
                "        \"Year\", \"CY'\" & CalendarDim[Year],",
                "        \"Year Order\", CalendarDim[Year],",
                "        \"Type\", \"Custom selections\",",
                "        \"Type Order\", 2,",
                "        \"Level\", \"Month\",",
                "        \"Level Order\", 3,",
                "        \"Element\", CalendarDim[Month & Year],",
                "        \"Element Order\",",
                "            CALCULATE ( MAX ( CalendarDim[MonthnYear] ) ) * 1000",
                "                + CALCULATE (",
                "                    COUNTROWS ( CalendarDim ),",
                "                    ALLEXCEPT ( CalendarDim, CalendarDim[MonthnYear] )",
                "                )",
                "    )",
                "",
                "VAR _Weeks =",
                "    SELECTCOLUMNS (",
                "        CalendarDim,",
                "        \"Date\", CalendarDim[Date],",
                "        \"Year\", \"CY'\" & CalendarDim[Year],",
                "        \"Year Order\", CalendarDim[Year],",
                "        \"Type\", \"Custom selections\",",
                "        \"Type Order\", 2,",
                "        \"Level\", \"Week\",",
                "        \"Level Order\", 4,",
                "        \"Element\", CalendarDim[Fiscal Year & Week],",
                "        \"Element Order\",",
                "            CALCULATE ( MAX ( CalendarDim[FWeeknYear] ) ) * 1000",
                "                + CALCULATE (",
                "                    COUNTROWS ( CalendarDim),",
                "                    ALLEXCEPT ( CalendarDim, CalendarDim[FWeeknYear] )",
                "                )",
                "    )",
                "",
                "VAR _CurrentDate =",
                "    TODAY ()",
                "VAR _YesterdayDate =",
                "    TODAY () - 1",
                "VAR _2DaysPriorToTodayDate = ",
                "     TODAY() - 2",
                "",
                "",
                "VAR _CurrentMonthStartDate =",
                "    DATE ( YEAR ( _CurrentDate ), MONTH ( _CurrentDate ), 1 )",
                "VAR _CurrentMonthEndDate =",
                "    EOMONTH ( _CurrentMonthStartDate, 0 )",
                "",
                "VAR vrPriorWeekStartDate =",
                " CALCULATE(MIN(DimTempCalendar[Date]), ALLNOBLANKROW(DimTempCalendar), DimTempCalendar[WeekOffset] = -1)",
                "VAR vrPriorWeekEndDate =",
                " CALCULATE(MAX(DimTempCalendar[Date]), ALLNOBLANKROW(DimTempCalendar), DimTempCalendar[WeekOffset] = -1)",
                "VAR vrPrior2WeekStartDate =",
                " CALCULATE(MIN(DimTempCalendar[Date]), ALLNOBLANKROW(DimTempCalendar), DimTempCalendar[WeekOffset] = -2)",
                "VAR vrPrior2WeekEndDate =",
                " CALCULATE(MAX(DimTempCalendar[Date]), ALLNOBLANKROW(DimTempCalendar), DimTempCalendar[WeekOffset] = -2)",
                "",
                " ",
                " ",
                "VAR _PriorWeekStartDate =",
                "     DATE ( YEAR ( vrPriorWeekStartDate ), MONTH ( vrPriorWeekStartDate ), DAY(vrPriorWeekStartDate) )",
                "  VAR _PriorWeekEndDate =",
                "     DATE ( YEAR ( vrPriorWeekEndDate ), MONTH ( vrPriorWeekEndDate ), DAY(vrPriorWeekEndDate) )",
                "  ",
                "VAR _Prior2WeekStartDate =",
                "     DATE ( YEAR ( vrPrior2WeekStartDate ), MONTH ( vrPrior2WeekStartDate ), DAY(vrPrior2WeekStartDate) )",
                "  VAR _Prior2WeekEndDate =",
                "     DATE ( YEAR ( vrPrior2WeekEndDate ), MONTH ( vrPrior2WeekEndDate ), DAY(vrPrior2WeekEndDate) )  ",
                "",
                "VAR _Today =",
                "    ROW (",
                "        \"Date\", _CurrentDate,",
                "        \"Year\", \"Today\",",
                "        \"Year Order\", 1,",
                "        \"Type\", \"Predefined selections\",",
                "        \"Type Order\", 1,",
                "        \"Level\", \"Today\",",
                "        \"Level Order\", 1,",
                "        \"Element\", \"Today\",",
                "        \"Element Order\",",
                "            YEAR ( _CurrentDate ) * 100000",
                "                + MONTH ( _CurrentDate ) * 1000",
                "                + DAY ( _CurrentDate )",
                "    )",
                "VAR _Yesterday =",
                "    ROW (",
                "        \"Date\", _YesterdayDate,",
                "        \"Year\", \"Yesterday\",",
                "        \"Year Order\", 2,",
                "        \"Type\", \"Predefined selections\",",
                "        \"Type Order\", 1,",
                "        \"Level\", \"Yesterday\",",
                "        \"Level Order\", 1,",
                "        \"Element\", \"Yesterday\",",
                "        \"Element Order\",",
                "            YEAR ( _YesterdayDate ) * 100000",
                "                + MONTH ( _YesterdayDate ) * 1000",
                "                + DAY ( _YesterdayDate )",
                "    )",
                "",
                "VAR _2DaysPrior =",
                "    ROW (",
                "        \"Date\", _2DaysPriorToTodayDate,",
                "        \"Year\", \"2 Days Prior\",",
                "        \"Year Order\", 3,",
                "        \"Type\", \"Predefined selections\",",
                "        \"Type Order\", 1,",
                "        \"Level\", \"2 Days Prior\",",
                "        \"Level Order\", 1,",
                "        \"Element\", \"2 Days Prior\",",
                "        \"Element Order\",",
                "            YEAR ( _2DaysPriorToTodayDate ) * 100000",
                "                + MONTH ( _2DaysPriorToTodayDate ) * 1000",
                "                + DAY ( _2DaysPriorToTodayDate )",
                "    )",
                "",
                "",
                "VAR _CurrentMonth =",
                "    FILTER (",
                "        SELECTCOLUMNS (",
                "            CalendarDim,",
                "            \"Date\", CalendarDim[Date],",
                "            \"Year\", \"Current Month\",",
                "            \"Year Order\", 3,",
                "            \"Type\", \"Predefined selections\",",
                "            \"Type Order\", 1,",
                "            \"Level\", \"Current Month\",",
                "            \"Level Order\", 1,",
                "            \"Element\", \"Current Month\",",
                "            \"Element Order\",",
                "                YEAR ( _CurrentMonthEndDate ) * 100000",
                "                    + MONTH ( _CurrentMonthEndDate ) * 1000",
                "                    + DAY ( _CurrentMonthEndDate )",
                "        ),",
                "        [Date] >= _CurrentMonthStartDate",
                "            && [Date] <= _CurrentMonthEndDate",
                "    )",
                "",
                "VAR _PriorWeek =",
                "    FILTER (",
                "        SELECTCOLUMNS (",
                "            CalendarDim,",
                "            \"Date\", CalendarDim[Date],",
                "            \"Year\", \"Prior Week\",",
                "            \"Year Order\", 4,",
                "            \"Type\", \"Predefined selections\",",
                "            \"Type Order\", 1,",
                "            \"Level\", \"Prior Week\",",
                "            \"Level Order\", 1,",
                "            \"Element\", \"Prior Week\",",
                "            \"Element Order\",",
                "                YEAR ( _PriorWeekEndDate ) * 100000",
                "                    + MONTH ( _PriorWeekEndDate ) * 1000",
                "                    + DAY ( _PriorWeekEndDate )",
                "        ),",
                "        [Date] >= _PriorWeekStartDate",
                "            && [Date] <= _PriorWeekEndDate",
                "    )",
                "",
                "",
                "VAR _Prior2Week =",
                "    FILTER (",
                "        SELECTCOLUMNS (",
                "            CalendarDim,",
                "            \"Date\", CalendarDim[Date],",
                "            \"Year\", \"Prior 2 Week\",",
                "            \"Year Order\", 5,",
                "            \"Type\", \"Predefined selections\",",
                "            \"Type Order\", 1,",
                "            \"Level\", \"Prior 2 Week\",",
                "            \"Level Order\", 1,",
                "            \"Element\", \"Prior 2 Week\",",
                "            \"Element Order\",",
                "                YEAR ( _Prior2WeekEndDate ) * 100000",
                "                    + MONTH ( _Prior2WeekEndDate ) * 1000",
                "                    + DAY ( _Prior2WeekEndDate )",
                "        ),",
                "        [Date] >= _Prior2WeekStartDate",
                "            && [Date] <= _Prior2WeekEndDate",
                "    )",
                "",
                "VAR _Result =",
                "    UNION ( _Years, _Quarters, _Months, _Weeks, _Today, _Yesterday, _2DaysPrior, ",
                "           _PriorWeek,",
                "           _Prior2Week,",
                "          _CurrentMonth )",
                "RETURN",
                "    _Result"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_12d0e6fd-492e-4456-9da0-ce4568f6da6f",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f350c5cc-1c5a-4550-909f-ed26f7d75f88",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0de86354-446e-4f69-90db-78e65987b63c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4ecf18fd-f1fb-4245-97ae-f56d7015acc1",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "24fff42d-9c27-4c8e-b384-aaa508cd410c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "34ac77c7-7186-444d-9dbe-f8225cfce0a8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "40207140-a5e8-4bb9-963e-647d5f2433a0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3314d75f-454d-4dce-adb9-524692445ace",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "262fae96-4676-4d97-945a-a0ee7c1e615b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "523908de-a7c3-4cce-882e-89f4b2de66de",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e0e5569b-be1e-47c5-9b76-666878b89188",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8510b2b2-f990-449c-96e7-0c3d2194e7e8",
                "ordinal": 3
              }
            ],
            "lineageTag": "3491e2bf-7afb-40d6-ba6a-06c35db6e566"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "a52649cf-ee4e-4a6b-8705-3714cef9a6b2",
        "partitions": [
          {
            "name": "DateTableTemplate_12d0e6fd-492e-4456-9da0-ce4568f6da6f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DimCompanyCalendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3821c20b-01d7-4f58-bb22-41f185be1347",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3fa67135-8887-4ca5-b512-3cd29ffd656c"
                },
                "isDefault": true,
                "relationship": "64c72c42-78a0-4cfe-a93c-67dcbdd7e73e"
              }
            ]
          },
          {
            "name": "DateInt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "6d407c00-523a-4978-af1a-6fe05c467ba8",
            "sourceColumn": "DateInt",
            "summarizeBy": "sum"
          },
          {
            "name": "Day Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e39b78b-b262-408a-8968-5454f3c783aa",
            "sourceColumn": "Day Type",
            "summarizeBy": "none"
          },
          {
            "name": "DayOfMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "aca763c1-340e-4788-8f12-b642a3a0bfd3",
            "sourceColumn": "DayOfMonth",
            "summarizeBy": "sum"
          },
          {
            "name": "DayOfWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0f229f51-eb7a-485e-b489-1624ca764f98",
            "sourceColumn": "DayOfWeek",
            "summarizeBy": "sum"
          },
          {
            "name": "DayOfWeekName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3de3e60d-a2fa-4072-941d-410b8872ee91",
            "sourceColumn": "DayOfWeekName",
            "summarizeBy": "none"
          },
          {
            "name": "FPeriodnYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "24270a67-50c3-42ec-b6d7-9ad2be56ceb4",
            "sourceColumn": "FPeriodnYear",
            "summarizeBy": "sum"
          },
          {
            "name": "FQuarternYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e07a9b4c-3e7a-4379-be47-7ad3ae4bc28d",
            "sourceColumn": "FQuarternYear",
            "summarizeBy": "sum"
          },
          {
            "name": "FWeeknYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ce63e84b-5ff3-4990-bf8b-9dcbe933d7ba",
            "sourceColumn": "FWeeknYear",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c4e93c42-9338-47e2-bf96-d8a28c80a817",
            "sourceColumn": "Fiscal Period",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15fdfa6b-60b0-45a1-a3bd-9d3689d6829a",
            "sourceColumn": "Fiscal Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6faf03dc-933b-4749-9f75-6b2a7afa5bf1",
            "sourceColumn": "Fiscal Week",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "59e2c7b8-ba08-4add-a303-f38869f6eca9",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year & Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea2e8876-4c57-447d-95da-98f1169472ed",
            "sourceColumn": "Fiscal Year & Week",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYearOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "62f2149e-1fc0-4926-b416-2188161b51d9",
            "sourceColumn": "FiscalYearOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "Holiday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da5a95cf-4e9f-4c5f-949c-5d052d8bc136",
            "sourceColumn": "Holiday",
            "summarizeBy": "none"
          },
          {
            "name": "IsAfterToday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f3919346-fdd0-4b7f-af3a-8b2146710015",
            "sourceColumn": "IsAfterToday",
            "summarizeBy": "none"
          },
          {
            "name": "IsBusinessDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "06387270-8eb7-4311-ba0d-d76d4df6a0c1",
            "sourceColumn": "IsBusinessDay",
            "summarizeBy": "none"
          },
          {
            "name": "IsCurrentFP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "fb4506dc-fc7c-45f8-87ce-078d9f791454",
            "sourceColumn": "IsCurrentFP",
            "summarizeBy": "none"
          },
          {
            "name": "IsCurrentFQ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "6b1e5bba-8124-41e1-90b8-4743529b7b90",
            "sourceColumn": "IsCurrentFQ",
            "summarizeBy": "none"
          },
          {
            "name": "IsCurrentFW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "bbfed796-8a78-4f51-bc89-b1f8487f25c6",
            "sourceColumn": "IsCurrentFW",
            "summarizeBy": "none"
          },
          {
            "name": "IsHoliday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15ebe563-d508-468e-b224-7e02f841a35d",
            "sourceColumn": "IsHoliday",
            "summarizeBy": "none"
          },
          {
            "name": "IsPFYTD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "64d9fb4b-bfa9-46cb-89ca-744450c4b53c",
            "sourceColumn": "IsPFYTD",
            "summarizeBy": "none"
          },
          {
            "name": "IsPYTD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c30b5dd9-9034-48ce-8f1a-5284f67a4723",
            "sourceColumn": "IsPYTD",
            "summarizeBy": "none"
          },
          {
            "name": "IsWorkingDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c3135aa0-0597-408d-8574-43700577b9fb",
            "sourceColumn": "IsWorkingDay",
            "summarizeBy": "none"
          },
          {
            "name": "Month & Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "134ced60-f622-48b0-a4e8-aee90f773e7b",
            "sourceColumn": "Month & Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month Initial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "92268e54-4a45-4049-8de1-90f22d289f42",
            "sourceColumn": "Month Initial",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a24bb9b6-5f89-41e9-bbeb-fbd11ac1a917",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "MonthCompleted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "36a2ac6d-609b-4dc2-925a-5f7370e6c8aa",
            "sourceColumn": "MonthCompleted",
            "summarizeBy": "none"
          },
          {
            "name": "MonthEnding",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "de647f65-8733-4849-b0a7-7ec767e0c6d2",
            "sourceColumn": "MonthEnding",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_bd4d86f6-db01-4148-a8f6-f9e31fc2819d"
                },
                "isDefault": true,
                "relationship": "ee6ed064-033d-464f-8e82-f6db1e90ecfa"
              }
            ]
          },
          {
            "name": "MonthOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "26184e57-92c6-4063-bd1d-d254105b5a69",
            "sourceColumn": "MonthOfYear",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "71c25a9f-c0e8-4a49-8807-a42a34a958cb",
            "sourceColumn": "MonthOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthShortName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44f9f84a-660f-4c4a-8c02-4a5fa86a6999",
            "sourceColumn": "MonthShortName",
            "summarizeBy": "none"
          },
          {
            "name": "MonthStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "713ba486-b7e9-472f-9d4e-ff3b70e220ad",
            "sortByColumn": "MonthStatusSort",
            "sourceColumn": "MonthStatus",
            "summarizeBy": "none"
          },
          {
            "name": "MonthStatusSort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30b9df76-0f58-45fd-bc27-67b667edb7e9",
            "sourceColumn": "MonthStatusSort",
            "summarizeBy": "none"
          },
          {
            "name": "MonthnYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2329b2af-8c5e-4c21-a5c6-2d5c89922ba0",
            "sourceColumn": "MonthnYear",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter & Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6a359d8-2834-4ca1-872a-301be156fe1a",
            "sourceColumn": "Quarter & Year",
            "summarizeBy": "none"
          },
          {
            "name": "QuarterCompleted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "8db1e143-c89f-4f3a-813c-b240be40cc6d",
            "sourceColumn": "QuarterCompleted",
            "summarizeBy": "none"
          },
          {
            "name": "QuarterOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4ff13a91-5581-4008-907e-734967c45d54",
            "sourceColumn": "QuarterOfYear",
            "summarizeBy": "sum"
          },
          {
            "name": "QuarterOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7315483c-690f-4697-be6f-8d1d95f2a06a",
            "sourceColumn": "QuarterOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "QuarternYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "05591b81-c919-4f78-a8e0-5351298613db",
            "sourceColumn": "QuarternYear",
            "summarizeBy": "sum"
          },
          {
            "name": "WeekCompleted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f2de0caf-4d54-4434-845c-5b47cb473119",
            "sourceColumn": "WeekCompleted",
            "summarizeBy": "none"
          },
          {
            "name": "WeekEnding",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b0920ea5-6b64-4ed6-9723-c212306aaf3a",
            "sourceColumn": "WeekEnding",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3e9b4695-ff28-4bf9-bc58-7478673a3459"
                },
                "isDefault": true,
                "relationship": "8665f144-3286-4ea9-b143-54a15a86269b"
              }
            ]
          },
          {
            "name": "WeekEndingStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "beddcef3-4c58-494c-9e29-9e2ba0580f6c",
            "sourceColumn": "WeekEndingStatus",
            "summarizeBy": "none"
          },
          {
            "name": "WeekOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "84f7fa08-2f37-4e75-9643-8fff32e0bc6e",
            "sourceColumn": "WeekOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "WeekStarting",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "54c52d66-8612-482e-95b5-a5c9d7e16127",
            "sourceColumn": "WeekStarting",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_70e5ebaf-3fa2-440e-8f06-30b629a83ad1"
                },
                "isDefault": true,
                "relationship": "5908360d-b513-4339-b786-2ed2621df810"
              }
            ]
          },
          {
            "name": "WeekStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "b15b4447-fce3-4d7a-8c79-5493432bf9ed",
            "sortByColumn": "WeekStatusSort",
            "sourceColumn": "WeekStatus",
            "summarizeBy": "none"
          },
          {
            "name": "WeekStatusSort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "659ca8c1-71a2-4e27-b24c-2c2144698590",
            "sourceColumn": "WeekStatusSort",
            "summarizeBy": "none"
          },
          {
            "name": "Weekday Initial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7247d719-ca3f-4554-90cc-b93d8e695a72",
            "sourceColumn": "Weekday Initial",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5fde5ded-3364-46d2-86cb-83a15e55891f",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "YearCompleted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "65563e02-4aa3-4949-a17a-95d5ea23c660",
            "sourceColumn": "YearCompleted",
            "summarizeBy": "none"
          },
          {
            "name": "YearOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4256ef9b-294f-428d-a71e-e7ecccb01090",
            "sourceColumn": "YearOffset",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "59550784-5b73-41ba-842b-741c1462d2ca",
        "measures": [
          {
            "name": "Min Week Selected",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "MIN(CalendarDim[WeekOffset])",
            "lineageTag": "e5d92937-5b59-4e49-87bd-e062c5636fca"
          },
          {
            "name": "Max Week Selected",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "MAX(CalendarDim[WeekOffset])",
            "lineageTag": "1d54d11d-bc39-4a63-994d-5d2cbc16ec3c"
          },
          {
            "name": "Max Week Ending Date",
            "expression": "MAX(CalendarDim[WeekEnding])",
            "formatString": "General Date",
            "lineageTag": "558bbaa5-c991-4c7e-99c7-a0d21fdbc288"
          },
          {
            "name": "Min Week Ending Date",
            "expression": "MIN(CalendarDim[WeekEnding])",
            "formatString": "General Date",
            "lineageTag": "20b417e0-a2e7-4346-86c8-603ded6edf72"
          }
        ],
        "partitions": [
          {
            "name": "DimCompanyCalendar",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = fnBasicCalendarWithChoiceForStartOfWeek(#date(2020, 1, 1), #date(2025, 1, 1), 1, null, 0, 1),",
                "    #\"Merge With Holidays\" = Table.NestedJoin(Source, {\"Date\"}, HolidayTable, {\"Date\"}, \"HolidayTable\", JoinKind.LeftOuter),",
                "    #\"Expanded HolidayTable\" = Table.ExpandTableColumn(#\"Merge With Holidays\", \"HolidayTable\", {\"Holiday\"}, {\"Holiday\"}),",
                "    #\"Recognize Holiday\" = Table.ReplaceValue( #\"Expanded HolidayTable\", each [IsHoliday], each if  [Holiday] is null then \"No\" else [Holiday], ",
                "Replacer.ReplaceValue, {\"IsHoliday\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Recognize Holiday\", each [Date] >= #date(2021, 11, 1)),",
                "    add_month_status = Table.AddColumn(#\"Filtered Rows\", \"MonthStatus\", each if [MonthOffset] = 0 then \"Current Month\" else if [MonthOffset] = -1 then \"Past Month\" else [#\"Month & Year\"]),",
                "    add_month_status_sort = Table.AddColumn(add_month_status, \"MonthStatusSort\", each if [MonthStatus] = \"Current Month\" then 999999 else if [MonthStatus] = \"Past Month\" then 999998 else [MonthnYear]),",
                "    add_week_status = Table.AddColumn(add_month_status_sort, \"WeekStatus\", each if [WeekOffset] = 0 then \"Current Week\" else if [WeekOffset] = -1 then \"Past Week\" else [#\"Fiscal Year & Week\"]),",
                "    add_week_status_sort = Table.AddColumn(add_week_status, \"WeekStatusSort\", each if [WeekStatus] = \"Current Week\" then 999999 else if [WeekStatus] = \"Past Week\" then 999998 else [Fiscal Week]),",
                "",
                "    add_week_ending_status = Table.AddColumn(add_week_status_sort, \"WeekEndingStatus\", each if [WeekOffset] = 0 then \"Current Week\" & Date.ToText([WeekEnding]) else if [WeekOffset] = -1 then \"Past Week\" & Date.ToText([WeekEnding])  else Date.ToText([#\"WeekEnding\"])),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(add_week_ending_status,{{\"WeekEndingStatus\", type text}}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Changed Type\", each true)",
                "    //add_week_status_sort = Table.AddColumn(add_week_status, \"WeekStatusSort\", each if [WeekStatus] = \"Current Week\" then 999999 else if [WeekStatus] = \"Past Week\" then 999998 else [Fiscal Week]),",
                "    //#\"Changed Type\" = Table.TransformColumnTypes(add_week_status_sort,{{\"WeekStatusSort\", Int64.Type}})",
                "in",
                "    #\"Filtered Rows1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimTempCalendar",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "59ea91f3-e737-40d6-b90d-4a0d96e985e7",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_ab982fd3-afc9-4e1d-9add-ea2b435e4509"
                },
                "isDefault": true,
                "relationship": "93081f06-a4dd-4821-bce3-2bd88fab721d"
              }
            ]
          },
          {
            "name": "DateInt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "26ea1093-9b3b-4dc0-a617-c5a258394892",
            "sourceColumn": "DateInt",
            "summarizeBy": "sum"
          },
          {
            "name": "Day Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ede258b-1745-4101-a37a-acdb9dffee90",
            "sourceColumn": "Day Type",
            "summarizeBy": "none"
          },
          {
            "name": "DayOfMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fd79e51a-ea60-4133-a588-2a5da275cdcb",
            "sourceColumn": "DayOfMonth",
            "summarizeBy": "sum"
          },
          {
            "name": "DayOfWeek",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a9f515af-ee3f-4825-9a44-d8bc65001ecb",
            "sourceColumn": "DayOfWeek",
            "summarizeBy": "sum"
          },
          {
            "name": "DayOfWeekName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d0340ed0-4284-400c-9899-ce5364edba9c",
            "sourceColumn": "DayOfWeekName",
            "summarizeBy": "none"
          },
          {
            "name": "FPeriodnYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4cb06d93-144f-4afd-80a0-dfa16f6cca65",
            "sourceColumn": "FPeriodnYear",
            "summarizeBy": "sum"
          },
          {
            "name": "FQuarternYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "42b39266-ded7-49d1-81f0-48fe56c23eeb",
            "sourceColumn": "FQuarternYear",
            "summarizeBy": "sum"
          },
          {
            "name": "FWeeknYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1813f3eb-1562-465b-83e1-5cd2d66f9aaf",
            "sourceColumn": "FWeeknYear",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4bc17914-fd64-483e-a8ac-83f06f2858b6",
            "sourceColumn": "Fiscal Period",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "22f6c8c1-6036-4810-ad27-44e220cab1e3",
            "sourceColumn": "Fiscal Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8c4119a9-55c3-4928-8524-d463463a34c3",
            "sourceColumn": "Fiscal Week",
            "summarizeBy": "sum"
          },
          {
            "name": "Fiscal Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74898f57-0515-45c1-a20c-9138ccaf3a4b",
            "sourceColumn": "Fiscal Year",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Year & Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d65978c-ba27-4e5f-9e6e-a57651c5cace",
            "sourceColumn": "Fiscal Year & Week",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalYearOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4e17b930-befd-4d2c-affe-58b36c8ad85b",
            "sourceColumn": "FiscalYearOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "Holiday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "930a198f-c91d-443e-8eab-4949d08d8f31",
            "sourceColumn": "Holiday",
            "summarizeBy": "none"
          },
          {
            "name": "IsAfterToday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "5eb553ab-44c4-4e2c-9494-a9ba3d07089b",
            "sourceColumn": "IsAfterToday",
            "summarizeBy": "none"
          },
          {
            "name": "IsBusinessDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "ffaf43b6-8c10-4c14-99e7-55f6e4978aad",
            "sourceColumn": "IsBusinessDay",
            "summarizeBy": "none"
          },
          {
            "name": "IsCurrentFP",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c59e5230-8df1-4be6-a610-4e777111689d",
            "sourceColumn": "IsCurrentFP",
            "summarizeBy": "none"
          },
          {
            "name": "IsCurrentFQ",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c2086d79-aa39-45dc-9fac-a3a80f2c832f",
            "sourceColumn": "IsCurrentFQ",
            "summarizeBy": "none"
          },
          {
            "name": "IsCurrentFW",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "4969072c-1b3b-442b-95ad-7908cabfd8db",
            "sourceColumn": "IsCurrentFW",
            "summarizeBy": "none"
          },
          {
            "name": "IsHoliday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "412d104f-0382-4b69-ad57-aa8401940e03",
            "sourceColumn": "IsHoliday",
            "summarizeBy": "none"
          },
          {
            "name": "IsPFYTD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c6b83013-0714-4dcf-8397-d866438cdd5e",
            "sourceColumn": "IsPFYTD",
            "summarizeBy": "none"
          },
          {
            "name": "IsPYTD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "0199d19f-eaf2-448a-8759-b372f766fb56",
            "sourceColumn": "IsPYTD",
            "summarizeBy": "none"
          },
          {
            "name": "IsWorkingDay",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "9d02db08-820f-4775-bfd1-8865f7a98a2f",
            "sourceColumn": "IsWorkingDay",
            "summarizeBy": "none"
          },
          {
            "name": "Month & Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bdff31e5-58a2-446d-9b6e-8ed306dc8f22",
            "sourceColumn": "Month & Year",
            "summarizeBy": "none"
          },
          {
            "name": "Month Initial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e181584-104b-4da8-a774-d157223f6cf7",
            "sourceColumn": "Month Initial",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0940f923-e248-4820-9534-e73fc6acd5e1",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "MonthCompleted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "31581323-c9bf-4a57-9ef9-8fe68fb692aa",
            "sourceColumn": "MonthCompleted",
            "summarizeBy": "none"
          },
          {
            "name": "MonthEnding",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "47ab9219-cb81-462c-8ae6-fe49ab43b72c",
            "sourceColumn": "MonthEnding",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_41affdab-24ba-4b98-bfb2-94b749276feb"
                },
                "isDefault": true,
                "relationship": "5f11c854-b6f9-46d4-b7a1-5acf7f6f8792"
              }
            ]
          },
          {
            "name": "MonthOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "54dbdb2c-84b0-480a-af3d-e8dc5c0002d1",
            "sourceColumn": "MonthOfYear",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "762e5db0-cd50-4a12-802b-556a5d1b134f",
            "sourceColumn": "MonthOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "MonthShortName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d432532-834d-4005-8b2a-ea454f20b8b1",
            "sourceColumn": "MonthShortName",
            "summarizeBy": "none"
          },
          {
            "name": "MonthStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96cef70e-06c8-43d9-9457-a2955dbeebcf",
            "sourceColumn": "MonthStatus",
            "summarizeBy": "none"
          },
          {
            "name": "MonthStatusSort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "abb367c0-117e-42d4-84a6-bb4feefc4f47",
            "sourceColumn": "MonthStatusSort",
            "summarizeBy": "none"
          },
          {
            "name": "MonthnYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "af444c7e-a2e0-408b-acf3-f4093b4052c1",
            "sourceColumn": "MonthnYear",
            "summarizeBy": "sum"
          },
          {
            "name": "Quarter & Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ddba13d-0f5f-4894-86e6-68b488b50a90",
            "sourceColumn": "Quarter & Year",
            "summarizeBy": "none"
          },
          {
            "name": "QuarterCompleted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "04e4347d-31d9-472b-ab65-adf97b2bf949",
            "sourceColumn": "QuarterCompleted",
            "summarizeBy": "none"
          },
          {
            "name": "QuarterOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7d917a70-c3de-41f4-b708-200387e520e2",
            "sourceColumn": "QuarterOfYear",
            "summarizeBy": "sum"
          },
          {
            "name": "QuarterOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2b251107-930f-4ce7-a88f-439e18c8b4b9",
            "sourceColumn": "QuarterOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "QuarternYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "039f5758-aaac-4872-9aa8-fa1efbb6a01e",
            "sourceColumn": "QuarternYear",
            "summarizeBy": "sum"
          },
          {
            "name": "WeekCompleted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "8bea59f4-1085-48bf-bb2a-578a8a53ef85",
            "sourceColumn": "WeekCompleted",
            "summarizeBy": "none"
          },
          {
            "name": "WeekEnding",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3b3ca4d1-91ea-4876-befb-6eb18c491110",
            "sourceColumn": "WeekEnding",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_bacab686-3a2c-4c0e-bb54-cd74a8b36057"
                },
                "isDefault": true,
                "relationship": "24956400-5c65-488c-b0f2-e1295ba6e1a8"
              }
            ]
          },
          {
            "name": "WeekEndingStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4efc30e2-df6e-48a4-b9f4-a8f8bb5d1aee",
            "sourceColumn": "WeekEndingStatus",
            "summarizeBy": "none"
          },
          {
            "name": "WeekOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bb765817-b4bb-4f38-b851-1c9ccb06430a",
            "sourceColumn": "WeekOffset",
            "summarizeBy": "sum"
          },
          {
            "name": "WeekStarting",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "89aa0ee9-9cc1-4082-9d56-5e890cfc7928",
            "sourceColumn": "WeekStarting",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_bb75305e-0c47-41c5-a9c6-3f1154e2c3e1"
                },
                "isDefault": true,
                "relationship": "164fb63c-2b40-4566-b6f6-298e46e99b71"
              }
            ]
          },
          {
            "name": "WeekStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c2422af-8ffd-4ff9-8045-ffef1cd0005e",
            "sourceColumn": "WeekStatus",
            "summarizeBy": "none"
          },
          {
            "name": "WeekStatusSort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8cf92353-95c1-4208-9750-fe170d8bb394",
            "sourceColumn": "WeekStatusSort",
            "summarizeBy": "none"
          },
          {
            "name": "Weekday Initial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c39370a9-d420-4dd5-bf65-5627c707f2e4",
            "sourceColumn": "Weekday Initial",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "28237a00-2550-4335-8885-4f33a9542149",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "YearCompleted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "ca3e4a6d-f6e7-4cb1-996f-4291b21a3524",
            "sourceColumn": "YearCompleted",
            "summarizeBy": "none"
          },
          {
            "name": "YearOffset",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "8a9d06aa-2085-4b53-8ff4-75ebec1454fe",
            "sourceColumn": "YearOffset",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "eadee0f2-29f4-4890-8ca6-03794f0e6360",
        "partitions": [
          {
            "name": "DimTempCalendar",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = fnBasicCalendarWithChoiceForStartOfWeek(#date(2020, 1, 1), #date(2025, 1, 1), 1, null, 0, 1),",
                "    #\"Merge With Holidays\" = Table.NestedJoin(Source, {\"Date\"}, HolidayTable, {\"Date\"}, \"HolidayTable\", JoinKind.LeftOuter),",
                "    #\"Expanded HolidayTable\" = Table.ExpandTableColumn(#\"Merge With Holidays\", \"HolidayTable\", {\"Holiday\"}, {\"Holiday\"}),",
                "    #\"Recognize Holiday\" = Table.ReplaceValue( #\"Expanded HolidayTable\", each [IsHoliday], each if  [Holiday] is null then \"No\" else [Holiday], ",
                "Replacer.ReplaceValue, {\"IsHoliday\"}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Recognize Holiday\", each [Date] >= #date(2021, 11, 1)),",
                "    add_month_status = Table.AddColumn(#\"Filtered Rows\", \"MonthStatus\", each if [MonthOffset] = 0 then \"Current Month\" else if [MonthOffset] = -1 then \"Past Month\" else [#\"Month & Year\"]),",
                "    add_month_status_sort = Table.AddColumn(add_month_status, \"MonthStatusSort\", each if [MonthStatus] = \"Current Month\" then 999999 else if [MonthStatus] = \"Past Month\" then 999998 else [MonthnYear]),",
                "    add_week_status = Table.AddColumn(add_month_status_sort, \"WeekStatus\", each if [WeekOffset] = 0 then \"Current Week\" else if [WeekOffset] = -1 then \"Past Week\" else [#\"Fiscal Year & Week\"]),",
                "    add_week_status_sort = Table.AddColumn(add_week_status, \"WeekStatusSort\", each if [WeekStatus] = \"Current Week\" then 999999 else if [WeekStatus] = \"Past Week\" then 999998 else [Fiscal Week]),",
                "",
                "    add_week_ending_status = Table.AddColumn(add_week_status_sort, \"WeekEndingStatus\", each if [WeekOffset] = 0 then \"Current Week\" & Date.ToText([WeekEnding]) else if [WeekOffset] = -1 then \"Past Week\" & Date.ToText([WeekEnding])  else Date.ToText([#\"WeekEnding\"])),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(add_week_ending_status,{{\"WeekEndingStatus\", type text}}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Changed Type\", each true)",
                "    //add_week_status_sort = Table.AddColumn(add_week_status, \"WeekStatusSort\", each if [WeekStatus] = \"Current Week\" then 999999 else if [WeekStatus] = \"Past Week\" then 999998 else [Fiscal Week]),",
                "    //#\"Changed Type\" = Table.TransformColumnTypes(add_week_status_sort,{{\"WeekStatusSort\", Int64.Type}})",
                "in",
                "    #\"Filtered Rows1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "HolidayTable",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "bfba9f79-4919-432f-aff6-32c81c9b1376",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c0cfca0c-ee8c-48e9-b62b-99d84d38ca0f"
                },
                "isDefault": true,
                "relationship": "d42fd728-1117-43dd-999c-ed6f9d398df9"
              }
            ]
          },
          {
            "name": "Holiday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1069a17-92fb-4595-a997-8ce625c64c36",
            "sourceColumn": "Holiday",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c52d2c64-6e0b-41e0-b8e5-a1b03713e512",
        "partitions": [
          {
            "name": "HolidayTable",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"fZLBaoNAEIZfRTwH1h1jrde2CS00pZBSKDaHaTNE0eyGXY307SvobEq6evEw3/zjOJ95HkohBUQQh4vwhbrgg9B8tlEEqQ0e8CfcLfIQhATu2bYnMsGd7mpGS0bvWJNqSkXX+aVIuOcVrdVnMmM94/oKbdPP3bZqP4b6iKMbOmpTYu0m3gh5y3CNTUH/dk6F2+tJ7elE/UN9k+PZhT/jlzYOyEjE7iKPWNe6I1ID6usxo7cCVWUP5blUh4GCSC851VYVFgzAHeC+MKVtjmgD98bkzw032vcxoyOYdxRzz4QjmHckE266kiRTBj5LccTUZyljOGsJpi25pSYsgdeSm+qzNPw6MKkJpjS5nMfS7hc=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Date = _t, Holiday = _t]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(Source,{{\"Date\", type date}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_3e9b4695-ff28-4bf9-bc58-7478673a3459",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9ad14d17-4b77-45a4-9f85-73a5301f1849",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "86bfdca4-e658-4b69-9326-c1d5a120a463",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "025b9ca2-af32-48fb-8902-90f98e72f4bc",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2810a2c1-308b-42fb-80b4-49edbc46e284",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2f8f2ea4-4f93-49d3-a09f-d277873cdaf5",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4370f9b5-40ba-4727-a9f0-bb800e32848d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "266d1757-3fa5-4514-b41b-bde4f1095081",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "988b67bb-93ba-4a63-b23a-8e31e6cc27dc",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "49dc20e0-b68f-4ed2-a0ff-71fc2e10dbfa",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ba9d00ff-fc49-47be-b912-6404e1d64cb3",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "5d60c2ad-daec-4191-998e-2ce07bb172d9",
                "ordinal": 3
              }
            ],
            "lineageTag": "746e640e-a255-46e9-80ea-329af08e3274"
          }
        ],
        "isHidden": true,
        "lineageTag": "53d4afa8-42ab-4e3a-85a2-95d9571b7e78",
        "partitions": [
          {
            "name": "LocalDateTable_3e9b4695-ff28-4bf9-bc58-7478673a3459",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimCompanyCalendar'[WeekEnding])), 1, 1), Date(Year(MAX('DimCompanyCalendar'[WeekEnding])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_3fa67135-8887-4ca5-b512-3cd29ffd656c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d5453cf4-6402-444e-a754-5c62b54e1f1e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cb646412-d633-454c-9479-e2e8f5b8feab",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6958ceca-15b0-4dc6-950b-3e50f583cbce",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bd26643e-ec43-42b0-bd26-2a3cc36e1238",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "48665606-53cc-401c-b305-0f43e1b4069c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9575920e-4ff9-43af-ae6d-4806dbf6aa64",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fa4f9e1c-7012-422c-afe6-53bc13b56c46",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "963b6f89-9c2d-4a69-997e-2de61a4d1d51",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "90d74167-aa8c-4b1d-9e8e-12db71e3f6c4",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c028052c-f738-45eb-9cc0-f5334d78abe7",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8e8b9908-b571-49a3-bb8f-ea6f1ee82cfa",
                "ordinal": 3
              }
            ],
            "lineageTag": "fc6e3718-576c-480b-9a8a-4630d8b2825f"
          }
        ],
        "isHidden": true,
        "lineageTag": "3891f08d-bb19-43d6-b278-2ca5e2a9c71c",
        "partitions": [
          {
            "name": "LocalDateTable_3fa67135-8887-4ca5-b512-3cd29ffd656c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimCompanyCalendar'[Date])), 1, 1), Date(Year(MAX('DimCompanyCalendar'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_41affdab-24ba-4b98-bfb2-94b749276feb",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "02e431d9-dd4e-4859-8a14-8be1b86a6985",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "86a2b644-aa3b-4c69-bb00-81cabfa3b295",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5a31f672-0656-40e4-8ae8-a7b74c57157b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2ab3a041-8eba-4f6a-8aa7-824ebfe16f04",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2c2b0047-c397-4690-b75d-4402302479ef",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "af473757-2142-4a9f-a8dc-30f9fc36a7e4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "098c9332-b222-4ce4-8e5b-e4541cf6dc26",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f110e7ba-4689-4a28-95f2-eb6e71ace4b0",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "af0a5591-9639-4100-be1e-222172396cb8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "a544a047-613d-4380-b66b-741c4c5ca2c4",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "74f12771-9991-4502-9846-efa7686eebc8",
                "ordinal": 3
              }
            ],
            "lineageTag": "24be36cb-b39e-49be-ba53-9dd17e5acc19"
          }
        ],
        "isHidden": true,
        "lineageTag": "338ec42c-b74e-44f6-8c2b-e84e48c566d5",
        "partitions": [
          {
            "name": "LocalDateTable_41affdab-24ba-4b98-bfb2-94b749276feb",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimTempCalendar'[MonthEnding])), 1, 1), Date(Year(MAX('DimTempCalendar'[MonthEnding])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_6ac7e5d7-ee96-487d-b0d6-114a6a43211a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "85933af6-421b-4d2a-b1df-8dac9557142f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0ed24ec0-6658-4ac2-a74e-b037a097a5fd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "be41a306-b26a-49f9-865d-4eedb02aecbd",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "24aff144-1cc8-4c43-b95c-3d852eb3a1a8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b801b1aa-56fa-4a01-a195-686e40c04f24",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f3d900ae-e12b-42fc-bb14-9b3726b89c1e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f60c51ad-aef8-4280-9b0e-1c2d2b21a0f4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f5cd7a77-f69a-4cfa-9491-5ee096bbc793",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "65fb7965-b616-427c-b0dd-14a8dc3c22f4",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "bbdec1e2-a39e-4dba-a805-0a6e2705d340",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e1bc2258-48a9-4498-b85f-a7178d397dff",
                "ordinal": 3
              }
            ],
            "lineageTag": "dd1d2a98-d103-4b6d-bfb7-fec8ef1a6417"
          }
        ],
        "isHidden": true,
        "lineageTag": "684314cc-862c-469d-a59c-476d471c94a1",
        "partitions": [
          {
            "name": "LocalDateTable_6ac7e5d7-ee96-487d-b0d6-114a6a43211a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('CalendarDim'[WeekEnding])), 1, 1), Date(Year(MAX('CalendarDim'[WeekEnding])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_70e5ebaf-3fa2-440e-8f06-30b629a83ad1",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d42cc3ed-ea1d-4503-9291-708803db2c0f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c8e6d095-d412-4d28-b92a-9a467b1e1dc6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "704e7219-eb54-40f5-ab1b-2fedd335d677",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8ca714c0-6d71-4a73-9972-b41edd7adb86",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f443a773-1c39-4eee-8225-87ba5bae3537",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e06fb024-7f6d-4540-b042-c2e529f72941",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6088b1f2-d1c9-43b0-8d5c-7caf316d473b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1789c78e-841b-48c3-a259-986a105ce59d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a4938776-4a57-490c-8214-bbc338bd02af",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0d278007-aa0d-4d46-b3ce-d1424bb82955",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "411b8b5f-b5af-47e6-92ac-e012304fb81b",
                "ordinal": 3
              }
            ],
            "lineageTag": "58f9468b-bcba-4a0b-bab1-83d02a807ffb"
          }
        ],
        "isHidden": true,
        "lineageTag": "3fcfc15e-3a27-486f-90eb-63418453450a",
        "partitions": [
          {
            "name": "LocalDateTable_70e5ebaf-3fa2-440e-8f06-30b629a83ad1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimCompanyCalendar'[WeekStarting])), 1, 1), Date(Year(MAX('DimCompanyCalendar'[WeekStarting])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_ab982fd3-afc9-4e1d-9add-ea2b435e4509",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5ec2016f-661a-42e7-852d-04fb45eec298",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e31b4599-db7b-4ab7-a350-6f3ad4f68670",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a7744511-78ea-4e72-9d16-7f9ceaf5a495",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "717dd3ab-1292-487b-a2b6-9155c9726089",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7b693ac4-755e-4cae-83e9-6d18517e5b7f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1e73d7d6-3a5e-4a8e-81ab-66d3027c8e6b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b1904afb-0e41-4d9f-9c83-6a52c16e0ece",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "8bb3e05e-3e8b-4831-aa4e-dadf0ca13152",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "f6448173-e639-4aa0-9736-b0eb6d5a8fd2",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1efac6a3-cbc5-4de4-8d26-e8746d8778b5",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "5a5f1f9a-2288-4446-836b-4d30a72caa20",
                "ordinal": 3
              }
            ],
            "lineageTag": "e95ab61e-6dd8-472f-8550-a3b15e2b51a6"
          }
        ],
        "isHidden": true,
        "lineageTag": "df6129d4-ea66-4636-b270-1f641cba3014",
        "partitions": [
          {
            "name": "LocalDateTable_ab982fd3-afc9-4e1d-9add-ea2b435e4509",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimTempCalendar'[Date])), 1, 1), Date(Year(MAX('DimTempCalendar'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_bacab686-3a2c-4c0e-bb54-cd74a8b36057",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "742cea29-4ec0-4cb8-bfcc-d7b2656cfb0f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "50e7b440-3b1e-4d52-aa05-c10cbacbe9f0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6542e169-8a58-444c-8b65-70c36562c4a9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9d2de4a4-6935-40e9-a2ce-50499b602d52",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7a208f79-eaeb-4e14-8acd-5ccf5d46e449",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3f2814e0-2d86-4270-849d-faf02f8c5fd1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "31101c08-b644-4777-9610-3bb7bc798789",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f5870917-5584-4b46-bbd9-a06e5c4d805a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "83c0329b-3777-4e3b-808e-df700f373ac3",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4aaf7caf-fb9d-4779-a5d7-a2773831501b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1cabf76d-2bbe-4fe0-b370-67fa6ccb3459",
                "ordinal": 3
              }
            ],
            "lineageTag": "2ca78400-73f9-4a67-ab2b-98844f2043f6"
          }
        ],
        "isHidden": true,
        "lineageTag": "7b2a90fe-592d-4545-a195-d8ee9698ef9e",
        "partitions": [
          {
            "name": "LocalDateTable_bacab686-3a2c-4c0e-bb54-cd74a8b36057",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimTempCalendar'[WeekEnding])), 1, 1), Date(Year(MAX('DimTempCalendar'[WeekEnding])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_bb75305e-0c47-41c5-a9c6-3f1154e2c3e1",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ddae116f-cfac-4ea3-af46-abac73e4ea86",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1800400d-8d99-4268-bdcf-b9bb39cdb398",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b8da6558-4cf7-4d9f-9811-600715aaed35",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f435f004-aa6d-4b77-bad4-1b7b92840c78",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "55eddedb-b7f3-4bff-9217-b752a0400491",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5a6e8b7f-d5d6-44f9-863a-1b9e1275b0dd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e06ddc40-5f37-409d-a606-a20d4fd08e28",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "27a5a907-3f4f-4a9d-91b6-543783566549",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "5980c684-dddf-48db-ac43-0d5bfb575e44",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "4593f4f5-b54f-4810-a11d-cade8a7d1faf",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "add0144e-b1c1-4cc6-93d4-cd6a3176fc9f",
                "ordinal": 3
              }
            ],
            "lineageTag": "35698158-3574-4e95-a4a3-4d2b029394a0"
          }
        ],
        "isHidden": true,
        "lineageTag": "4b83c358-9c40-40c9-906b-be89eac0788e",
        "partitions": [
          {
            "name": "LocalDateTable_bb75305e-0c47-41c5-a9c6-3f1154e2c3e1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimTempCalendar'[WeekStarting])), 1, 1), Date(Year(MAX('DimTempCalendar'[WeekStarting])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_bd4d86f6-db01-4148-a8f6-f9e31fc2819d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6f45bd49-9528-451d-9ab4-83343075de54",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3ed55b20-a0a8-473a-bc6a-77448c901ea3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7915a302-b284-4a37-9818-f6943734f27d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b267a477-7a79-49c5-aca1-235f94ea67b3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "02724f15-9e45-4846-bb02-c828ef0d5e7a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0327098d-e1be-473f-ae9f-4612c92c0231",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5f807b55-a08b-496b-866c-506e18f01081",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1e07978a-df36-4b16-97a6-726a048f412d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "bf75e5b8-2cc4-47f1-a741-5ae21ac37619",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "b6afd031-145e-481a-bedb-1568bd232575",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ac0e9154-fdf9-430b-9fc4-81eb30c43e3a",
                "ordinal": 3
              }
            ],
            "lineageTag": "6f5b1d7c-4c9e-4782-9218-8d33b1782879"
          }
        ],
        "isHidden": true,
        "lineageTag": "ce7aa5c2-aa2e-4824-a442-05fbb79bee9a",
        "partitions": [
          {
            "name": "LocalDateTable_bd4d86f6-db01-4148-a8f6-f9e31fc2819d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DimCompanyCalendar'[MonthEnding])), 1, 1), Date(Year(MAX('DimCompanyCalendar'[MonthEnding])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_c0cfca0c-ee8c-48e9-b62b-99d84d38ca0f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c8e804af-f3f1-4ca8-b269-042a194a84b6",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "989cd293-08f6-4e6b-bf00-ee207cd5611c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "45ff484d-5e77-4b67-8695-7870d7882ee7",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "44ac18b2-deb7-46d3-b46c-402a739884a4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "684795ee-5189-4d57-937f-3405a8ac6a8c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "964a97ff-447b-4a7c-ad68-de31f017ff99",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "971c49ac-51bb-47aa-ade2-2bef289de45b",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "ad40d1b5-0aa9-4510-8f80-d3b3d7d18b6c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "5f9ce21f-9092-4da6-8dee-ade100e9d78c",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1568a79c-923f-4a0f-8258-77ae35d431b9",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "56bd695d-705b-4ccd-9a8c-841c49c3030b",
                "ordinal": 3
              }
            ],
            "lineageTag": "28bf23c5-bb7d-4f47-9448-bee6ecad2e67"
          }
        ],
        "isHidden": true,
        "lineageTag": "9a66dabf-25f2-42df-a3f0-b493a09bc927",
        "partitions": [
          {
            "name": "LocalDateTable_c0cfca0c-ee8c-48e9-b62b-99d84d38ca0f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('HolidayTable'[Date])), 1, 1), Date(Year(MAX('HolidayTable'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e1326a3f-5d35-4b27-a455-f1d7ca3cbbb0",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b3dfc21b-3ae9-4504-b1b6-335424076df9",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "392ecfee-79a2-4cca-90d7-ee241375ddde",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f048bdc9-9b55-43bb-8256-ba1bc5bb7a8f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "e5217a1c-b628-44a1-8f90-766b0700c02b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "430571a0-8ae6-4706-b21c-dd82992d4c91",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8adc6e58-9a4e-4091-a1bb-87a09e7f7dd8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3c5c0d9a-f811-4229-b73b-4aa7d1597246",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "669dac91-0421-4273-a3d3-4b126aa0c6dc",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "47395058-e6dc-4588-a371-fada739cb90b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "9c93ffe3-cab4-4299-aca8-5ae1adeb7c43",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7eb83ea7-246f-4329-bb89-3d373ce9a4c3",
                "ordinal": 3
              }
            ],
            "lineageTag": "760c3c86-37d4-48e0-8215-2b4b0615b561"
          }
        ],
        "isHidden": true,
        "lineageTag": "a309a0bc-695e-4c60-aa74-258c1c7edb0f",
        "partitions": [
          {
            "name": "LocalDateTable_e1326a3f-5d35-4b27-a455-f1d7ca3cbbb0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('CalendarDim'[Date])), 1, 1), Date(Year(MAX('CalendarDim'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e171ca97-92d3-4760-a286-aa64125a152c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2a4ca4d0-d22a-493c-8125-52322ced408c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2b096d27-45ab-4dbd-a455-58dc3935a912",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ce8f8603-729c-42b7-9d22-82c93a90daef",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b2cb12b6-9461-47ac-b0e9-b3102608185e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f6010946-4f04-48a4-a6af-91a82f316dd4",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "edd3a9c4-4c66-49a7-bdd4-2a2d31950a0e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f3825db4-708e-47e8-aaf6-ba24464f2169",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1c6a0c94-da6c-4a10-aa82-fa93b700884e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "437aaf8e-9cf9-4042-81e8-7f59fb85d80b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f59301ad-d870-490a-82c1-844ab2e03fa9",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8c9a62b6-a551-4407-9830-2312deb27c2c",
                "ordinal": 3
              }
            ],
            "lineageTag": "f7de662e-31d5-4c05-9561-13bf95f30ee2"
          }
        ],
        "isHidden": true,
        "lineageTag": "100d8d75-6ac7-41c2-a202-c9bcf57b888f",
        "partitions": [
          {
            "name": "LocalDateTable_e171ca97-92d3-4760-a286-aa64125a152c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('CalendarDim'[WeekStarting])), 1, 1), Date(Year(MAX('CalendarDim'[WeekStarting])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}